//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentinglatest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voiture()
        {
            this.location = new HashSet<location>();
        }
    
        public string immatriculation { get; set; }
        public Nullable<int> modele { get; set; }
        public Nullable<int> categorie { get; set; }
        public Nullable<System.DateTime> date_mec { get; set; }
        public string carburant { get; set; }
        public Nullable<decimal> prix_loc { get; set; }
        public string image { get; set; }
    
        public virtual categorie categorie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> location { get; set; }
        public virtual modele modele1 { get; set; }
    }
}
